# Generated by Django 5.1.1 on 2024-09-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=10000),
        ),
    ]
